---
- hosts: nodes
  roles:
    #- common
    #- docker
    #- { role: anxs.postgresql, when: zabbix_server, become: true }
    #- { role: dj-wasabi.zabbix-server, when: zabbix_server, become: true }
    #- { role: dj-wasabi.zabbix-web, when: zabbix_server, become: true }
    - { role: dj-wasabi.zabbix-agent, become: true }
    #- kubernetes
    #- beam
    #- consul-agent
